### ISSUE TITLE
Write a first automated test on listing all requirements in a folder.

### ISSUE THREAD

**Issue by oerich** [regot-chalmers/treqs#11]
This is a subtask of #5 and is supposed to test whether #10 implements #9 

## What needs to be done? 
Define an automated unit test in Python.

## Under which condition will this be considered completed?
- Test executes
- Test is linked

**Comment by oerich** [comment]
Also relates to #25

**Comment by Godsmith** [comment]
Solved by https://review.gerrithub.io/#/c/regot-chalmers/treqs/+/422490
