### ISSUE TITLE
As a treqs admin I want to add user story ids to my user story so that I can automatically process the story tracing offline.

### ISSUE THREAD

**Issue by grischal** [regot-chalmers/treqs#21]
[userstory id=US20]

_As a_ treqs admin _I want to_ add user story ids to my user story _so that_ I can automatically process the story tracing offline.

**Comment by Godsmith** [comment]
Closing this because it does not have any id, and it looks a bit strange for the demo. We can reopen it and give it an id if it is relevant after the demo.
