### ISSUE TITLE
Make example complete: real T-Reqs reqts, real tests, and scripts

### ISSUE THREAD

**Issue by oerich** [regot-chalmers/treqs#25]
## What needs to be done? 
Look at all requirements, scripts, tests

Real task: update manual and automated tests; e.g. adding a new user story on github could be a manual test.

## Under which condition will this be considered completed?
Example feels real.

**Comment by Godsmith** [comment]
When https://review.gerrithub.io/c/regot-chalmers/treqs/+/422416 is merged, I think I have completed this task, because then both the dummy manual test case and the dummy automatic test case are replaced with real ones.
