### ISSUE TITLE
Compile a step-by-step guide for demo

### ISSUE THREAD

**Issue by oerich** [regot-chalmers/treqs#26]
## What needs to be done? 

Write step by step what needs to be done for demo. Clearly relates to manual test cases for each user story. Select one, two, three user stories, but otherwise be flexible.

Might need some of the basic stuff, also things that are outside our scripts (gerrit, github tasks).

**Comment by Godsmith** [comment]
I think this is fulfilled by TC3 and TC4, currently in review at https://review.gerrithub.io/c/regot-chalmers/treqs/+/422432 .

**Comment by oerich** [comment]
I agree, there is also [an old wiki page](https://github.com/regot-chalmers/treqs/wiki/Demonstrator), though.

Perhaps we could make the interplay of user stories and manual tests explicit there?
