### ISSUE TITLE
Write initial system requirements

### ISSUE THREAD

**Issue by oerich** [regot-chalmers/treqs#3]
## What needs to be done? 

Create system requirements for each user story in #2. Use and refine template. Create subtasks per user story?

## Under which condition will this be considered completed?

- Some proof (traceability matrix?) that all user stories are covered.

**Comment by oerich** [comment]
Relates to #25

**Comment by Godsmith** [comment]
With change https://review.gerrithub.io/c/regot-chalmers/treqs/+/422432, all existing user stories are covered.
