### ISSUE TITLE
Define a small number of tests

### ISSUE THREAD

**Issue by oerich** [regot-chalmers/treqs#5]
## What needs to be done? 

Based on system requirements (#3), write a small set of tests (not necessarily automated tests?). Use and refine template. Provide some links.

## Under which condition will this be considered completed?
TBD

**Comment by oerich** [comment]
Relates to #25

**Comment by Godsmith** [comment]
Solved by https://review.gerrithub.io/#/c/regot-chalmers/treqs/+/422490 and some other changes in Gerrit
